@ECHO OFF
ECHO Novo texto!
ECHO OUTRA MENSAGEM 
ECHO MAIS OUTRA MENSAGEM
ECHO
ECHO ======================
ECHO MODIFICAÇÃO FEITA PELA BRANCH DEVELOP
ECHO ======================
ECHO
ECHO ======================
ECHO MODIFICAÇÃO FEITA NA BRANCH MAIN 
ECHO ======================
ECHO 
ECHO O OBEJETIVO DESTA MODIFICAÇÃO É GERAR CONFLITO COM A MODIFICAÇÃO
ECHO QUE SERA FEITA NA BRANCH DEVELOP
ECHO
PAUSE
