@ECHO OFF
ECHO Novo texto!
ECHO OUTRA MENSAGEM 
ECHO MAIS OUTRA MENSAGEM
ECHO
ECHO ======================
ECHO MODIFICAÇÃO FEITA PELA BRANCH DEVELOP
ECHO ======================
ECHO 
ECHO CONFLITO SOLUCIONADO
PAUSE
