@ECHO OFF
ECHO Novo texto!
ECHO OUTRA MENSAGEM 
ECHO MAIS OUTRA MENSAGEM

ECHO ======================
ECHO MODIFICAÇÃO FEITA PELA BRANCH DEVELOP
ECHO ======================
ECHO 
ECHO ======================
ECHO MODIFICÃCAO FEITA PELA BRANCH DEVELOP
ECHO ======================
ECHO 
ECHO ORIGEM DO CONFLITO 
ECHO 
PAUSE
